// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv5nTR229JDoAUG4QqUJ8sOwtOFYT0QdY',
    appId: '1:267758672045:web:4bb333fcbd92450d3dce24',
    messagingSenderId: '267758672045',
    projectId: 'portfolio-chrisbp',
    authDomain: 'portfolio-chrisbp.firebaseapp.com',
    storageBucket: 'portfolio-chrisbp.appspot.com',
    measurementId: 'G-QV6XF45D2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBroKXcxIqLVZlY81PYtpS2mRIbNBZ_fX8',
    appId: '1:267758672045:android:6a897cbd687564dc3dce24',
    messagingSenderId: '267758672045',
    projectId: 'portfolio-chrisbp',
    storageBucket: 'portfolio-chrisbp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeZGnvaQ0Lg7AbKUpTtcNPPQysT8-oWoE',
    appId: '1:267758672045:ios:0799212b1d782d823dce24',
    messagingSenderId: '267758672045',
    projectId: 'portfolio-chrisbp',
    storageBucket: 'portfolio-chrisbp.appspot.com',
    iosBundleId: 'com.chrisbp.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeZGnvaQ0Lg7AbKUpTtcNPPQysT8-oWoE',
    appId: '1:267758672045:ios:0799212b1d782d823dce24',
    messagingSenderId: '267758672045',
    projectId: 'portfolio-chrisbp',
    storageBucket: 'portfolio-chrisbp.appspot.com',
    iosBundleId: 'com.chrisbp.portfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCv5nTR229JDoAUG4QqUJ8sOwtOFYT0QdY',
    appId: '1:267758672045:web:d6258140e57d7fc03dce24',
    messagingSenderId: '267758672045',
    projectId: 'portfolio-chrisbp',
    authDomain: 'portfolio-chrisbp.firebaseapp.com',
    storageBucket: 'portfolio-chrisbp.appspot.com',
    measurementId: 'G-VT5Y5TR8DP',
  );
}
